In [3]:
import pandas as pd
import numpy as np

In [2]:
#####7.1 Handling Missing Data

In [3]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [27]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [8]:
string_data[0] = None

In [9]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [10]:
from numpy import nan as NA

In [11]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [20]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA, NA], [NA, NA, NA], [NA,6.5,3.]])

In [21]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [24]:
cleaned = data.dropna()

In [25]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [28]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [30]:
data[4] = NA

In [31]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [32]:
data.dropna(axis=1, how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [45]:
df = pd.DataFrame(np.random.randn(7,3,))

In [46]:
df

0         1         2
0  0.468937 -0.732796 -1.316013
1  1.061713  0.178893 -0.725356
2 -1.087665 -0.287119 -0.187055
3 -0.895124 -0.965470 -0.152023
4 -0.276552  0.344024  1.283176
5 -1.555676 -0.734715 -1.481246
6  2.139317  1.180464 -1.198571

In [47]:
df.iloc[:4,1] = NA

In [48]:
df

0         1         2
0  0.468937       NaN -1.316013
1  1.061713       NaN -0.725356
2 -1.087665       NaN -0.187055
3 -0.895124       NaN -0.152023
4 -0.276552  0.344024  1.283176
5 -1.555676 -0.734715 -1.481246
6  2.139317  1.180464 -1.198571

In [49]:
df.iloc[:2, 2] = NA

In [50]:
df

0         1         2
0  0.468937       NaN       NaN
1  1.061713       NaN       NaN
2 -1.087665       NaN -0.187055
3 -0.895124       NaN -0.152023
4 -0.276552  0.344024  1.283176
5 -1.555676 -0.734715 -1.481246
6  2.139317  1.180464 -1.198571

In [51]:
df.dropna()

0         1         2
4 -0.276552  0.344024  1.283176
5 -1.555676 -0.734715 -1.481246
6  2.139317  1.180464 -1.198571

In [52]:
df.dropna(thresh=2) ####drop rows 2 or more NA

0         1         2
2 -1.087665       NaN -0.187055
3 -0.895124       NaN -0.152023
4 -0.276552  0.344024  1.283176
5 -1.555676 -0.734715 -1.481246
6  2.139317  1.180464 -1.198571

In [58]:
df.fillna(0)

0         1         2
0  0.468937  0.000000  0.000000
1  1.061713  0.000000  0.000000
2 -1.087665  0.000000 -0.187055
3 -0.895124  0.000000 -0.152023
4 -0.276552  0.344024  1.283176
5 -1.555676 -0.734715 -1.481246
6  2.139317  1.180464 -1.198571

In [60]:
df.fillna({1:0.5, 2:0}) ###fillna can fill specific nmber, funny

0         1         2
0  0.468937  0.500000  0.000000
1  1.061713  0.500000  0.000000
2 -1.087665  0.500000 -0.187055
3 -0.895124  0.500000 -0.152023
4 -0.276552  0.344024  1.283176
5 -1.555676 -0.734715 -1.481246
6  2.139317  1.180464 -1.198571

In [61]:
df = pd.DataFrame(np.random.randn(6,3))

In [62]:
df.iloc[2:, 1] = NA

In [63]:
df.iloc[4:, 2] = NA

In [64]:
df

0         1         2
0 -0.185135  0.729027 -0.604391
1 -1.600161 -0.284622 -0.000896
2 -0.694761       NaN  0.164533
3  2.044535       NaN -0.972619
4 -2.082389       NaN       NaN
5 -1.098314       NaN       NaN

In [65]:
df.fillna(method='ffill')

0         1         2
0 -0.185135  0.729027 -0.604391
1 -1.600161 -0.284622 -0.000896
2 -0.694761 -0.284622  0.164533
3  2.044535 -0.284622 -0.972619
4 -2.082389 -0.284622 -0.972619
5 -1.098314 -0.284622 -0.972619

In [66]:
df.fillna(method='ffill', limit=2) ###ffill = forward fill

0         1         2
0 -0.185135  0.729027 -0.604391
1 -1.600161 -0.284622 -0.000896
2 -0.694761 -0.284622  0.164533
3  2.044535 -0.284622 -0.972619
4 -2.082389       NaN -0.972619
5 -1.098314       NaN -0.972619

In [67]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [68]:
data.fillna(data.mean()) ###NA space contains average

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [69]:
#####7.2 Data Transformation

In [70]:
data = pd.DataFrame({'k1': ['one', 'two'] *3+['two'], 
                    'k2':[1,1,2,3,3,4,4]})

In [71]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [72]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [73]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [74]:
data['v1'] = range(7)

In [75]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [76]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [77]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [2]:
######Transforming Data Using a Function or Mapping

In [3]:
data = pd.DataFrame({'food':['bacon', 'pulled pork','bacon',
                            'Pastrami','corned beef', 'Bacon',
                            'pastrami', 'honey ham', 'nova lox'], 
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [4]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [10]:
meat_to_animal = {'bacon':'pig', 'pulled pork':'pig', 'pastrami':'cow',
                 'corned beef':'cow', 'honey ham':'pig', 'nova lox':'salmon'}

In [11]:
lowercased = data['food'].str.lower()

In [12]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [13]:
data['animal']=lowercased.map(meat_to_animal)

In [14]:
data ####Keeping  capitalize4d food name ,but can correpsond b/c food converted to lower case.

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [15]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [16]:
#####Replacing Values

In [19]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [20]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [21]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [22]:
data.replace([-999,-1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [23]:
data.replace([-999,-1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [25]:
data.replace({-999:np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [26]:
###Renaming Axis Index

In [28]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado','New York'],
                    columns=['one', 'two','three','four'])

In [29]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [30]:
transform = lambda x : x[:4].upper()

In [31]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [32]:
data.index = data.index.map(transform)

In [33]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [34]:
data.rename(index = str.title, columns=str.upper) ###What is str.title??

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [36]:
data.rename(index = {'OHIO':'INDIANA'}, columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [37]:
data.rename(index = {'OHIO':'INDIANA'}, inplace=True) ###What significant??

In [38]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [3]:
#####Discretization  and Binning

In [4]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [5]:
bins = [18, 25, 35, 60, 100]

In [6]:
cats = pd.cut(ages, bins)

In [7]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [8]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [9]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [10]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [11]:
pd.cut(ages, [18, 26, 36, 61, 100], right = False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [13]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [14]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [15]:
data = np.random.rand(20)

In [16]:
pd.cut(data, 4, precision=2)

[(0.0069, 0.25], (0.73, 0.98], (0.25, 0.49], (0.49, 0.73], (0.25, 0.49], ..., (0.25, 0.49], (0.73, 0.98], (0.25, 0.49], (0.0069, 0.25], (0.0069, 0.25]]
Length: 20
Categories (4, interval[float64]): [(0.0069, 0.25] < (0.25, 0.49] < (0.49, 0.73] < (0.73, 0.98]]

In [17]:
data

array([0.1317489 , 0.97512642, 0.34712409, 0.55338342, 0.26691851,
       0.66521438, 0.13446687, 0.00787682, 0.17048958, 0.57564012,
       0.4687519 , 0.81343196, 0.42917502, 0.82644402, 0.42914383,
       0.349616  , 0.91767346, 0.3894452 , 0.03521516, 0.22554694])

In [18]:
data = np.random.randn(1000)

In [19]:
data

array([-3.10983190e-01, -1.30984585e+00, -6.84705790e-01, -8.93260305e-01,
       -3.95562464e-01, -1.09792471e-01,  1.63692027e+00,  2.77129417e-01,
       -2.74700521e+00, -2.10212309e+00,  9.35390993e-01, -5.55855771e-01,
        2.39103343e+00, -1.69491581e-01, -3.59255677e-01,  1.14066121e+00,
       -5.45660863e-01, -6.79630705e-01,  1.08853547e+00,  3.92904485e-01,
        1.80758919e-01, -1.18814913e+00,  1.06942931e+00, -5.15902639e-01,
        3.66806794e-01,  2.80042457e-01,  2.23696763e-01, -6.69902371e-01,
        8.26446313e-02, -7.99286659e-01,  1.74762300e+00, -6.44373259e-01,
       -1.00148985e+00,  1.44314658e+00, -5.56011157e-01,  4.60230082e-01,
        3.00339449e-01,  2.05799594e-02, -1.91446970e+00,  6.69838723e-01,
        4.68167795e-01, -4.02249237e-01, -4.20392009e-01,  1.01166744e+00,
        3.96241924e-02, -8.32373395e-01, -2.67126883e-01, -2.62129744e+00,
        7.20435237e-01,  2.14699553e-02, -1.25960148e-01, -6.93539064e-01,
        9.12670942e-01,  

In [20]:
cats = pd.qcut(data, 4)

In [21]:
cats

[(-0.656, -0.00434], (-3.199, -0.656], (-3.199, -0.656], (-3.199, -0.656], (-0.656, -0.00434], ..., (0.685, 2.867], (-0.656, -0.00434], (-0.00434, 0.685], (-3.199, -0.656], (-0.656, -0.00434]]
Length: 1000
Categories (4, interval[float64]): [(-3.199, -0.656] < (-0.656, -0.00434] < (-0.00434, 0.685] < (0.685, 2.867]]

In [22]:
pd.value_counts(cats)

(0.685, 2.867]        250
(-0.00434, 0.685]     250
(-0.656, -0.00434]    250
(-3.199, -0.656]      250
dtype: int64

In [23]:
pd.qcut(data, [0,0.1,0.5,0.9,1.])

[(-1.232, -0.00434], (-3.199, -1.232], (-1.232, -0.00434], (-1.232, -0.00434], (-1.232, -0.00434], ..., (-0.00434, 1.19], (-1.232, -0.00434], (-0.00434, 1.19], (-3.199, -1.232], (-1.232, -0.00434]]
Length: 1000
Categories (4, interval[float64]): [(-3.199, -1.232] < (-1.232, -0.00434] < (-0.00434, 1.19] < (1.19, 2.867]]