In [1]:
import pandas as pd
import numpy as np

In [2]:
#####Detecting and Filtering Outliers

In [3]:
data = pd.DataFrame(np.random.randn(1000,4))

In [4]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.068104    -0.031160     0.011634     0.007830
std       0.980993     0.999602     1.008016     1.024602
min      -2.832402    -3.162556    -3.230024    -3.155225
25%      -0.733501    -0.680897    -0.691033    -0.682295
50%      -0.087837    -0.022541     0.014900     0.024486
75%       0.574428     0.634908     0.703585     0.677151
max       3.235167     3.204113     3.787294     3.114690

In [5]:
col = data[2]

In [6]:
col[np.abs(col)>3]

473    3.398802
483   -3.230024
507    3.787294
Name: 2, dtype: float64

In [8]:
data[(np.abs(data)>3).any(1)] 

0         1         2         3
8    0.934692  0.175550  0.225162  3.114690
102 -0.330330  0.798176  0.006112 -3.128980
174  0.490521  1.606850 -2.214570 -3.155225
221  1.062988 -3.162556  0.928358 -0.085528
370  0.883327  3.106133 -0.925222  0.135209
473  0.143459  0.368261  3.398802  0.590823
483 -1.663057 -0.595931 -3.230024  0.270068
507 -0.121467  0.190742  3.787294  0.156875
543  3.235167 -0.481264 -0.892382 -0.328237
610 -1.244312 -3.123170 -0.296598  1.839166
809  3.079042 -1.301810  0.965820  0.067302
978  0.252174  3.204113 -0.289783  1.777370

In [13]:
data[np.abs(data>3)] = np.sign(data)*3  ###????, what is for???

In [14]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.068418    -0.031470     0.010448     0.007716
std       0.979977     0.998633     1.004101     1.024260
min      -2.832402    -3.162556    -3.230024    -3.155225
25%      -0.733501    -0.680897    -0.691033    -0.682295
50%      -0.087837    -0.022541     0.014900     0.024486
75%       0.574428     0.634908     0.703585     0.677151
max       3.000000     3.000000     3.000000     3.000000

In [15]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0 -1.0
1 -1.0  1.0  1.0  1.0
2 -1.0 -1.0 -1.0 -1.0
3 -1.0 -1.0  1.0 -1.0
4 -1.0  1.0  1.0  1.0

In [16]:
#####Permutation and Random Sampling

In [20]:
df = pd.DataFrame(np.arange(5 * 4).reshape(5, 4))

In [26]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [27]:
sampler = np.random.permutation(5)

In [28]:
sampler

array([1, 2, 0, 3, 4])

In [29]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15
4  16  17  18  19

In [30]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11

In [31]:
choices = pd.Series([5,7,-1,6,4])

In [33]:
draws = choices.sample(n = 10,replace=True)

In [34]:
draws

2   -1
0    5
2   -1
2   -1
4    4
0    5
0    5
4    4
2   -1
1    7
dtype: int64

In [35]:
#####Computing Indicator/Dummy Variables

In [2]:
df = pd.DataFrame({'key':['b', 'b', 'a', 'c', 'a', 'b'],
                  'data1':range(6)})

In [3]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [39]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [40]:
dummies = pd.get_dummies(df['key'], prefix = 'key')

In [41]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [44]:
df_with_dummy = df[['data1']].join(dummies)

In [45]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [4]:
mnames = ['movie','title','genres']

In [5]:
movies = pd.read_table('./pydata-book-2nd-edition/datasets/movielens/movies.dat', sep = '::',
                       header = None, names = mnames) ####What is the warning for ?

/Users/rie/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [6]:
movies[:10]

movie                               title                        genres
0      1                    Toy Story (1995)   Animation|Children's|Comedy
1      2                      Jumanji (1995)  Adventure|Children's|Fantasy
2      3             Grumpier Old Men (1995)                Comedy|Romance
3      4            Waiting to Exhale (1995)                  Comedy|Drama
4      5  Father of the Bride Part II (1995)                        Comedy
5      6                         Heat (1995)         Action|Crime|Thriller
6      7                      Sabrina (1995)                Comedy|Romance
7      8                 Tom and Huck (1995)          Adventure|Children's
8      9                 Sudden Death (1995)                        Action
9     10                    GoldenEye (1995)     Action|Adventure|Thriller

In [7]:
all_genres = []

In [8]:
for x in movies.genres:
    all_genres.extend(x.split('|')) 

In [10]:
genres = pd.unique(all_genres)

In [11]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [12]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [14]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [16]:
gen = movies.genres[0]

In [18]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [19]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [20]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [21]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [22]:
movies_windic.iloc[0]

movie                                          1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [23]:
np.random.seed(12345)

In [24]:
values = np.random.rand(10)

In [25]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [26]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [27]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [28]:
#####7.3 String Manupulation

In [29]:
###Stting Object Methods

In [30]:
val = 'a,b, guido'

In [31]:
val.split(',')

['a', 'b', ' guido']

In [32]:
pieces = [x.strip() for x in val.split(',')]

In [33]:
pieces

['a', 'b', 'guido']

In [34]:
first, second, third = pieces 

In [35]:
first + '::'+ second + '::' + third

'a::b::guido'

In [36]:
'::'.join(pieces)

'a::b::guido'

In [37]:
'guido' in val

True

In [38]:
val.index(',')

1

In [40]:
val.find(':') ???

-1

In [41]:
val.index(':')

ValueError: substring not found

In [42]:
val.count(',')

2

In [43]:
val.replace(',','::')

'a::b:: guido'

In [44]:
val.replace(',','')

'ab guido'

In [2]:
###Regular expresions

In [3]:
import re

In [6]:
text = "foo bar\t baz \tqux"  ###even this format can be compiled uniformly??

In [7]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [8]:
regex = re.compile('\s+')

In [9]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [10]:
regex.findall(text)

[' ', '\t ', ' \t']

In [12]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [15]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [18]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [19]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [20]:
m = regex.search(text)

In [21]:
m

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>

In [22]:
text[m.start():m.end()]

'dave@google.com'

In [23]:
print(regex.match(text))

None


In [24]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [36]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [37]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [38]:
m = regex.match('wesm@bright.net')

In [39]:
m.groups()

('wesm', 'bright', 'net')

In [40]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [41]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [42]:
###Vectorized String Functions in pandas

In [43]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
   .....:         'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [44]:
data = pd.Series(data)

In [45]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [46]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [47]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [63]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [64]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [69]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [66]:
matches

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [70]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [71]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [72]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN